language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run manage.py test --keepdb
  - python manage.py test --keepdb evap.evaluation.tests.test_misc.TestDataTest.load_test_data
  - python manage.py test --keepdb --reverse
  - python manage.py test --keepdb --debug-mode
after_success:
  - coveralls
sudo: false
cache:
  directories:
  - $HOME/.cache/pip
